---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/mysrini/pcf-attendee-service-code.git
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: api.system.cumuluslabs.io        #<----- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: sm2-PAL-JAN8    #<----- REPLACE ME
    space: sandbox         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: test-attendee-service
    trigger: true
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: test
  public: true
  plan:
  - get: attendee-service
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml
  - put: test-attendee-service

